// src/auth/decorators/roles.decorator.ts
import { SetMetadata } from '@nestjs/common';
import { Role } from '@prisma/client'; // Import the strict enum generated by Prisma

export const ROLES_KEY = 'roles';

// This decorator takes an array of strictly typed Roles
export const Roles = (...roles: Role[]) => SetMetadata(ROLES_KEY, roles);
